### ISSUE TITLE
bash support

### ISSUE THREAD

**Issue by cupcat121** [crosstyan/dreambooth-scripts-for-autodl#2]
share the bash script of mine used for recent days.  [fork here](https://github.com/NoSimpleApple/dreambooth-scripts-for-autodl/tree/bash-support)

## My env
bash:  `5.0.17(1)-release (x86_64-pc-linux-gnu)`
coreutils: `8.30-3ubuntu2`

## Feature
- many environment variables make things continuous
- entry options
- user settings as the a1111 webui's did

## Function
- training
- format converting between ckpt and diffuser's
- clean checkpoints

**Comment by crosstyan** [comment]
Actually I plan to migrate current training implementation from [yaml-config branch of CCRcmcpe/diffusers](https://github.com/CCRcmcpe/diffusers/tree/yaml-config) to the new [SCAL-SDT](https://github.com/CCRcmcpe/scal-sdt). I would try to add bash support by then and maybe I would check your fork out ~~since I can't write good bash script~~.

**Comment by cupcat121** [comment]
If there's anything needed, I can help within my limited bash capability.
